
[package]
name = "zaffre"
version = "0.0.1"
authors = ["Jordan Miner <jminer7@gmail.com>"]
description = "Zaffre is a 2D graphics library."
keywords = ["2d", "graphics"]
license = "MPL-2.0"

[dependencies]
glium = "0.14.0"
nalgebra = "0.8.2"
num = "0.1.32"
